name: Daily Tests

on:
  schedule:
    - cron: '0 0 * * *' # Test run every day at 00:00 UTC

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.3'

      - name: Xvfb
        run: |
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - name: Run Tests
        run: cd tests && go test . -v -shuffle on
