name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.19', '1.20', '1.21.x' ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Display Go version
        run: go version

      - name: Install dependencies
        run: |
          go get .
          go get github.com/hajimehoshi/ebiten/v2
          go get github.com/stretchr/testify

      - name: Build
        run: go build -v ./...

      - name: Testing, testing
        run: cd game && go test timer.go timer_test.go -v
