name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21.x' ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.3'

      - name: Display Go version
        run: go version

      - name: Install dependencies
        run: |
          go get github.com/hajimehoshi/ebiten/v2
          go get github.com/stretchr/testify
          sudo apt-get install libxrandr-dev

      - name: Build
        run: go build -v ./...

      - name: Testing, testing
        run: cd game && go test timer.go timer_test.go -v
